
name: 'Make Current Report'

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TexLive Dependencies
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            scheme-basic
            amsfonts amsmath
            babel biber biblatex bibtex bidi bitset booktabs
            collection-context collection-luatex collection-xetex csquotes
            ec
            fancyvrb filehook fontspec footnotehyper
            geometry graphics
            hyperref
            iftex
            letltxmacro listings lm lm-math lualatex-math luaotfload
            mathspec microtype
            natbib
            oberdiek
            parskip pdfescape polyglossia
            setspace
            tools
            ulem unicode-math upquote
            xcolor xurl
            zapfding

      - name: Install APT Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: librsvg2-bin
          version: 1.0

      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.1.12.2/pandoc-3.1.12.2-1-amd64.deb pandoc.deb
          dpkg -i pandoc.deb

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip' # caching pip dependencies

      - name: Install Python dependencies
        run: pip install -r current/requirements.txt

      - name: Make
        run: make -C current build

      #- name: Upload Report
        #uses: actions/upload-artifact@v4
        #with:
          #name: report
          #path: current/informe.pdf

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: current/dist

  deploy:
    needs: make

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
